mcpServers:
  fetch:
    command: "uvx"
    args: ["mcp-server-fetch"]
    description: "Access a webpage"
  "Filesystem Operations":
    command: "uvx"
    args: ["git+https://github.com/strawgate/py-mcp-collection.git#subdirectory=filesystem-operations-mcp"]
    description: "Access the local filesystem"
  tree-sitter:
    command: "uvx"
    args: ["--directory", ".", "mcp-server-tree-sitter"]