DEFAULT_SKIP_LIST = [
    "**/.?*/**",
    ".?*/**",  # exclude hidden folders
    "**/.?*",  # exclude hidden files
    "**/.git/**",
    ".git/*",
    "**/.svn/**",
    ".svn/*",
    "**/.mypy_cache/**",
    ".mypy_cache/*",
    "**/.pytest_cache/**",
    "*.pytest_cache/*",
    "**/__pycache__/**",
    "*__pycache__/*",
    "**/.venv/**",
    ".venv/*",
]

DEFAULT_SKIP_READ = [
    "*.pyc",
    "*.pyo",
    "*.pyd",
    "*.hg",
    "*.tox",
    "*.com",
    "*.class",
    "*.dll",
    "*.exe",
    "*.o",
    "*.so",
    "*.7z",
    "*.dmg",
    "*.gz",
    "*.iso",
    "*.jar",
    "*.rar",
    "*.tar",
    "*.zip",
    "*.msi",
    "*.sqlite",
    "*.DS_Store",
    "*.DS_Store?",
    "*._*",
    "*.Spotlight-V100",
    "*.Trashes",
    "*ehthumbs.db",
    "*Thumbs.db",
    "*desktop.ini",
    "*.bak",
    "*.swp",
    "*.swo",
    "*~",
    "*#",
]
